### ISSUE TITLE
CSS: Background image "jumps" when scrollbar appears

### ISSUE THREAD

**Issue by malenchite** [malenchite/rpg-manager#122]
When a page has enough content to cause the right-hand scrollbar to appear, the background image "jumps" in scale.

**Comment by RobeandHat** [comment]
I can't seem re-create this issue or I might be misunderstanding it.

**Comment by malenchite** [comment]
To reproduce it, try creating a character with a very long Data field - newlines are recognized now, so you can just press enter a bunch of times then put some letters at the end. Save the character. Go back to the character list screen and switch between two characters, one with a short Data field and the long one.
