### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by malenchite** [malenchite/rpg-manager#14]
We'll need to be able to persist some data across page loads. For example, when navigating to the Inventory page, we must keep track of which Character is selected for display, API calls, and so that when we return to the Character View page, we have the same character selected. Similar for going to the Create/Edit item page and returning to the Inventory page.

One option for this is session cookies (http://expressjs.com/en/resources/middleware/cookie-session.html) but we may want to investigate other available options.

**Comment by malenchite** [comment]
Did a little bit of research here and Local Storage is considered the "newer" way to do this sort of data persistence that isn't related to sessions or login info.

**Comment by RobeandHat** [comment]
Note: Looking into "session storage"

**Comment by malenchite** [comment]
If we're using local storage, the values (character ID, item ID) will need to be saved prior to the page being loaded when a navigation button is clicked. That value will then be loaded into the object data based into the render() function in htmlRoutes.
