### ISSUE TITLE
Change Example items or remove them

### ISSUE THREAD

**Issue by RobeandHat** [malenchite/rpg-manager#174]
Currently, the add item page has example 1 and 2. I can't think of a reason a player would use these. So they would either have to edit them or delete them for them to be useful. One solution would be to change these to something thematic; the other solution would be to remove them altogether.  Let me know what you all think

**Comment by malenchite** [comment]
You're right that the example entries should be removed at this point from the deployed server. I think they should stay in the seed, since that it there for developer purposes.
